
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox4;
	
	private global::Gtk.VBox vbox7;
	
	private global::Gtk.Fixed fixed2;
	
	private global::Gtk.Label inversionLabel;
	
	private global::Gtk.Label inversionStatusLabel;
	
	private global::Gtk.VBox vbox6;
	
	private global::Gtk.Button invertButton;
	
	private global::Gtk.HBox hbox6;
	
	private global::Gtk.Button aboutButton;
	
	private global::Gtk.Label copyrightLabel;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Mouse Scroll Inverse");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(9));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.vbox7 = new global::Gtk.VBox ();
		this.vbox7.Name = "vbox7";
		this.vbox7.Spacing = 6;
		// Container child vbox7.Gtk.Box+BoxChild
		this.fixed2 = new global::Gtk.Fixed ();
		this.fixed2.Name = "fixed2";
		this.fixed2.HasWindow = false;
		this.vbox7.Add (this.fixed2);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.fixed2]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.inversionLabel = new global::Gtk.Label ();
		this.inversionLabel.Name = "inversionLabel";
		this.inversionLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Inversion:");
		this.vbox7.Add (this.inversionLabel);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.inversionLabel]));
		w2.Position = 1;
		w2.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.inversionStatusLabel = new global::Gtk.Label ();
		this.inversionStatusLabel.Name = "inversionStatusLabel";
		this.inversionStatusLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("OFF");
		this.vbox7.Add (this.inversionStatusLabel);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.inversionStatusLabel]));
		w3.Position = 2;
		this.vbox4.Add (this.vbox7);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.vbox7]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.vbox6 = new global::Gtk.VBox ();
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 6;
		// Container child vbox6.Gtk.Box+BoxChild
		this.invertButton = new global::Gtk.Button ();
		this.invertButton.CanFocus = true;
		this.invertButton.Name = "invertButton";
		this.invertButton.UseUnderline = true;
		this.invertButton.BorderWidth = ((uint)(15));
		this.invertButton.Label = global::Mono.Unix.Catalog.GetString ("Invert");
		this.vbox6.Add (this.invertButton);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.invertButton]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox ();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.aboutButton = new global::Gtk.Button ();
		this.aboutButton.CanFocus = true;
		this.aboutButton.Name = "aboutButton";
		this.aboutButton.UseUnderline = true;
		this.aboutButton.Label = global::Mono.Unix.Catalog.GetString ("About");
		this.hbox6.Add (this.aboutButton);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.aboutButton]));
		w6.Position = 0;
		w6.Fill = false;
		this.vbox6.Add (this.hbox6);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox6]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		this.vbox4.Add (this.vbox6);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.vbox6]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.copyrightLabel = new global::Gtk.Label ();
		this.copyrightLabel.Name = "copyrightLabel";
		this.copyrightLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("© 2015");
		this.vbox4.Add (this.copyrightLabel);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.copyrightLabel]));
		w9.Position = 2;
		w9.Expand = false;
		w9.Fill = false;
		this.Add (this.vbox4);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 283;
		this.DefaultHeight = 208;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.invertButton.Clicked += new global::System.EventHandler (this.OnInvertButtonClicked);
		this.aboutButton.Clicked += new global::System.EventHandler (this.OnAboutButtonClicked);
	}
}
